//***************************************************************************
//                          pvapp.h  -  description
//                             -------------------
//  begin            : Mi Nov 8 11:58:45 2006
//  generated by     : pvdevelop (C) 2000-2006 by Lehrig Software Engineering
//  email            : lehrig@t-online.de
//***************************************************************************
#ifndef _PVAPP_H_
#define _PVAPP_H_

#include "processviewserver.h"
#include "rleventlogserver.h"
#include "rltime.h"
#include "rlcutil.h"
#include "rlsvganimator.h"
#include <math.h>

static int trace = 1;

#ifdef unix
#define LOGFILE "/var/log/pvbchat.log"
#else
#define LOGFILE NULL
#endif

#define ESC_KEY 16777216
#define PI 3.141592f
// todo: comment me out
//#include "rlmodbusclient.h"
//#include "rlsiemenstcpclient.h"
//#include "rlppiclient.h"
//#include "modbusdaemon.h"             // this is generated
//#include "siemensdaemon.h"            // this is generated
//#include "ppidaemon.h"                // this is generated

// these are our masks
enum {
  WELLCOME  = 1,
  CHAT1     = 2,
  PLOT1     = 3,
  MODAL1    = 4,
  TABLE1    = 5,
  SVG1      = 6,
  VTK1      = 7,
  GNUPLOT1  = 8,
  TREE1     = 9,
  SVG2      = 10,
  DWF2GL    = 11
};

// this is for SVG2 begin
typedef struct
{
  float x0, y0, x1, y1, scale, svgx0, svgy0;
  bool popup;
}
POPUP_DATA;

typedef struct
{
  float lifter_height;
}
SIMULATION_DATA;
// this is for SVG2 end

int initializeGL(PARAM *p);
int resizeGL(PARAM *p, int width, int height);

int show_mask11(PARAM *p);
int show_mask10(PARAM *p);
int show_mask9(PARAM *p);
int show_mask8(PARAM *p);
int show_mask7(PARAM *p);
int show_mask6(PARAM *p);
int show_mask5(PARAM *p);
int show_mask4(PARAM *p);
int show_mask3(PARAM *p);
int show_mask2(PARAM *p);
int show_mask1(PARAM *p);

#endif
