// include all headers from rllib
#ifndef _RLLIB_H
#define _RLLIB_H

#include "rlspawn.h"
#include "rlwthread.h"
#include "rlthread.h"
#include "rlsocket.h"
#include "rltime.h"
#include "rlmailbox.h"
#include "rlfifo.h"
#include "rlsharedmemory.h"
#include "rlspreadsheet.h"
#include "rlinifile.h"
#include "rlinterpreter.h"
#include "rlpcontrol.h"
#include "rlcutil.h"
#include "rldefine.h"
#include "rlevent.h"
#include "rleventlogserver.h"
#include "rldataprovider.h"
#include "rlserial.h"
#include "rlmodbus.h"
#include "rlmodbusclient.h"
#include "rl3964r.h"
#include "rlsiemenstcp.h"
#include "rlsiemenstcpclient.h"
#include "rlcontroller.h"
#include "rlppiclient.h"
#include "rlsvganimator.h"
#include "rlsvgcat.h"
#include "rlfileload.h"
#include "rlhistorylogger.h"
#include "rlhistoryreader.h"
//#include "rlhilschercif.h" // include this separately because it will produce warnings
#include "rludpsocket.h"
#include "rleibnetip.h"
#include "rlopcxmlda.h"
#include "rldataacquisition.h"
#include "rldataacquisitionprovider.h"
#include "rlstring.h"

#endif
