<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<title>Qwt User&#39;s Guide: QwtEventPattern::QwtEventPattern::MousePattern Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css">
<link href="doxygen.css" rel="stylesheet" type="text/css">
</head><body>
<!-- Generated by Doxygen 1.5.8 -->
<div class="navigation" id="top">
  <div class="tabs">
    <ul>
      <li><a href="index.html"><span>Main&nbsp;Page</span></a></li>
      <li><a href="pages.html"><span>Related&nbsp;Pages</span></a></li>
      <li class="current"><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>
    </ul>
  </div>
  <div class="tabs">
    <ul>
      <li><a href="annotated.html"><span>Class&nbsp;List</span></a></li>
      <li><a href="classes.html"><span>Class&nbsp;Index</span></a></li>
      <li><a href="hierarchy.html"><span>Class&nbsp;Hierarchy</span></a></li>
      <li><a href="functions.html"><span>Class&nbsp;Members</span></a></li>
    </ul>
  </div>
  <div class="navpath"><a class="el" href="class_qwt_event_pattern.html">QwtEventPattern</a>::<a class="el" href="class_qwt_event_pattern_1_1_mouse_pattern.html">MousePattern</a>
  </div>
</div>
<div class="contents">
<h1>QwtEventPattern::QwtEventPattern::MousePattern Class Reference</h1><!-- doxytag: class="QwtEventPattern::MousePattern" -->A pattern for mouse events.  
<a href="#_details">More...</a>
<p>
<code>#include &lt;<a class="el" href="qwt__event__pattern_8h-source.html">qwt_event_pattern.h</a>&gt;</code>
<p>

<p>
<a href="class_qwt_event_pattern_1_1_mouse_pattern-members.html">List of all members.</a><table border="0" cellpadding="0" cellspacing="0">
<tr><td></td></tr>
<tr><td colspan="2"><br><h2>Public Member Functions</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="6b9fe0cb474662aa5f18a58beb3e77d2"></a><!-- doxytag: member="QwtEventPattern::MousePattern::MousePattern" ref="6b9fe0cb474662aa5f18a58beb3e77d2" args="(int btn=Qt::NoButton, int st=Qt::NoButton)" -->
&nbsp;</td><td class="memItemRight" valign="bottom"><b>MousePattern</b> (int btn=Qt::NoButton, int st=Qt::NoButton)</td></tr>

<tr><td colspan="2"><br><h2>Public Attributes</h2></td></tr>
<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="c61a6548af6a963e654c5ca6df1c730f"></a><!-- doxytag: member="QwtEventPattern::MousePattern::button" ref="c61a6548af6a963e654c5ca6df1c730f" args="" -->
int&nbsp;</td><td class="memItemRight" valign="bottom"><b>button</b></td></tr>

<tr><td class="memItemLeft" nowrap align="right" valign="top"><a class="anchor" name="05ccef728a1b3c9f184551665e98c09d"></a><!-- doxytag: member="QwtEventPattern::MousePattern::state" ref="05ccef728a1b3c9f184551665e98c09d" args="" -->
int&nbsp;</td><td class="memItemRight" valign="bottom"><b>state</b></td></tr>

</table>
<hr><a name="_details"></a><h2>Detailed Description</h2>
A pattern for mouse events. </div>
<hr size="1"><address style="text-align: right;"><small>Generated on Sun Mar 22 16:41:21 2009 for Qwt User's Guide by&nbsp;
<a href="http://www.doxygen.org/index.html">
<img src="doxygen.png" alt="doxygen" align="middle" border="0"></a> 1.5.8 </small></address>
</body>
</html>
