#!/bin/sh
module="cif"
device="cif"
#group="Hilscher"
mode="664"

# invoke insmod with all arguments we got
/sbin/insmod -f $module.o $* || exit 1
##/sbin/insmod -f /home/cif/cif-v2.100/drv/$module.o dpm_add=0xd0000 dpm_len=2 irq=7 || exit 1

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

rm -f /dev/${device}
mknod /dev/${device} c $major 0

#chgrp $group /dev/${device}
#chmod $mode  /dev/${device}




