######################################################################
# Automatically generated by qmake (1.07a) Sat Apr 8 14:34:18 2006
######################################################################

TEMPLATE = app
CONFIG  += console warn_on release
CONFIG  -= qt
INCLUDEPATH += ../../rllib/rlhistory

# Input
# HEADERS +=
SOURCES     += ../../rllib/rlhistory/rlhistory.cpp
LIBS        += ../bin/rllib.lib
INCLUDEPATH += ../../rllib/lib
TARGET = rlhistory
