.TH "QwtClipper" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtClipper \- Some clipping algorithms\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "QWT_EXPORT void \fBclipPolygon\fP (const QRect &, QPolygon &, bool closePolygon=false)"
.br
.ti -1c
.RI "QWT_EXPORT void \fBclipPolygon\fP (const QRectF &, QPolygon &, bool closePolygon=false)"
.br
.ti -1c
.RI "QWT_EXPORT void \fBclipPolygonF\fP (const QRectF &, QPolygonF &, bool closePolygon=false)"
.br
.ti -1c
.RI "QWT_EXPORT QPolygon \fBclippedPolygon\fP (const QRect &, const QPolygon &, bool closePolygon=false)"
.br
.ti -1c
.RI "QWT_EXPORT QPolygon \fBclippedPolygon\fP (const QRectF &, const QPolygon &, bool closePolygon=false)"
.br
.ti -1c
.RI "QWT_EXPORT QPolygonF \fBclippedPolygonF\fP (const QRectF &, const QPolygonF &, bool closePolygon=false)"
.br
.ti -1c
.RI "QWT_EXPORT \fBQVector\fP< \fBQwtInterval\fP > \fBclipCircle\fP (const QRectF &, const QPointF &, double radius)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some clipping algorithms\&. 
.SH "Function Documentation"
.PP 
.SS "\fBQVector\fP< \fBQwtInterval\fP > QwtClipper::clipCircle (const QRectF & clipRect, const QPointF & center, double radius)"
Circle clipping
.PP
\fBclipCircle()\fP divides a circle into intervals of angles representing arcs of the circle\&. When the circle is completely inside the clip rectangle an interval [0\&.0, 2 * M_PI] is returned\&.
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIcenter\fP Center of the circle 
.br
\fIradius\fP Radius of the circle
.RE
.PP
\fBReturns\fP
.RS 4
Arcs of the circle 
.RE
.PP

.PP
Definition at line 477 of file qwt_clipper\&.cpp\&.
.SS "QPolygon QwtClipper::clippedPolygon (const QRect & clipRect, const QPolygon & polygon, bool closePolygon = \fCfalse\fP)"
Sutherland-Hodgman polygon clipping
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIpolygon\fP Polygon 
.br
\fIclosePolygon\fP True, when the polygon is closed
.RE
.PP
\fBReturns\fP
.RS 4
Clipped polygon 
.RE
.PP

.PP
Definition at line 437 of file qwt_clipper\&.cpp\&.
.SS "QPolygon QwtClipper::clippedPolygon (const QRectF & clipRect, const QPolygon & polygon, bool closePolygon = \fCfalse\fP)"
Sutherland-Hodgman polygon clipping
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIpolygon\fP Polygon 
.br
\fIclosePolygon\fP True, when the polygon is closed
.RE
.PP
\fBReturns\fP
.RS 4
Clipped polygon 
.RE
.PP

.PP
Definition at line 420 of file qwt_clipper\&.cpp\&.
.SS "QPolygonF QwtClipper::clippedPolygonF (const QRectF & clipRect, const QPolygonF & polygon, bool closePolygon = \fCfalse\fP)"
Sutherland-Hodgman polygon clipping
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIpolygon\fP Polygon 
.br
\fIclosePolygon\fP True, when the polygon is closed
.RE
.PP
\fBReturns\fP
.RS 4
Clipped polygon 
.RE
.PP

.PP
Definition at line 455 of file qwt_clipper\&.cpp\&.
.SS "void QwtClipper::clipPolygon (const QRect & clipRect, QPolygon & polygon, bool closePolygon = \fCfalse\fP)"
Sutherland-Hodgman polygon clipping
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIpolygon\fP Polygon IN/OUT 
.br
\fIclosePolygon\fP True, when the polygon is closed 
.RE
.PP

.PP
Definition at line 390 of file qwt_clipper\&.cpp\&.
.SS "void QwtClipper::clipPolygon (const QRectF & clipRect, QPolygon & polygon, bool closePolygon = \fCfalse\fP)"
Sutherland-Hodgman polygon clipping
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIpolygon\fP Polygon IN/OUT 
.br
\fIclosePolygon\fP True, when the polygon is closed 
.RE
.PP

.PP
Definition at line 369 of file qwt_clipper\&.cpp\&.
.SS "void QwtClipper::clipPolygonF (const QRectF & clipRect, QPolygonF & polygon, bool closePolygon = \fCfalse\fP)"
Sutherland-Hodgman polygon clipping
.PP
\fBParameters\fP
.RS 4
\fIclipRect\fP Clip rectangle 
.br
\fIpolygon\fP Polygon IN/OUT 
.br
\fIclosePolygon\fP True, when the polygon is closed 
.RE
.PP

.PP
Definition at line 404 of file qwt_clipper\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
