.TH "QwtPickerClickRectMachine" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPickerClickRectMachine \- A state machine for rectangle selections\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_picker_machine\&.h>\fP
.PP
Inherits \fBQwtPickerMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPickerClickRectMachine\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fBQList\fP< \fBCommand\fP > \fBtransition\fP (const \fBQwtEventPattern\fP &, const QEvent *) override"
.br
.RI "Transition\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A state machine for rectangle selections\&. 

Pressing \fBQwtEventPattern::MouseSelect1\fP starts the selection, releasing it selects the first point\&. Pressing it again selects the second point and terminates the selection\&. Pressing \fBQwtEventPattern::KeySelect1\fP also starts the selection, a second press selects the first point\&. A third one selects the second point and terminates the selection\&.
.PP
\fBSee also\fP
.RS 4
\fBQwtEventPattern::MousePatternCode\fP, \fBQwtEventPattern::KeyPatternCode\fP 
.RE
.PP

.PP
Definition at line 140 of file qwt_picker_machine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
