.TH "QwtPickerDragPointMachine" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtPickerDragPointMachine \- A state machine for point selections\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_picker_machine\&.h>\fP
.PP
Inherits \fBQwtPickerMachine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtPickerDragPointMachine\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fBQList\fP< \fBCommand\fP > \fBtransition\fP (const \fBQwtEventPattern\fP &, const QEvent *) override"
.br
.RI "Transition\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A state machine for point selections\&. 

Pressing \fBQwtEventPattern::MouseSelect1\fP or \fBQwtEventPattern::KeySelect1\fP starts the selection, releasing \fBQwtEventPattern::MouseSelect1\fP or a second press of \fBQwtEventPattern::KeySelect1\fP terminates it\&. 
.PP
Definition at line 118 of file qwt_picker_machine\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
