.TH "QwtSplineG1" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtSplineG1 \- Base class for spline interpolations providing a first order geometric continuity ( G1 ) between adjoining curves\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_spline\&.h>\fP
.PP
Inherits \fBQwtSplineInterpolating\fP\&.
.PP
Inherited by \fBQwtSplineC1\fP, and \fBQwtSplinePleasing\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtSplineG1\fP ()"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual \fB~QwtSplineG1\fP ()"
.br
.RI "Destructor\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class for spline interpolations providing a first order geometric continuity ( G1 ) between adjoining curves\&. 
.PP
Definition at line 216 of file qwt_spline\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
