.TH "QwtCPointerValueData< T >" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtCPointerValueData< T > \- Data class containing a pointer to memory of y coordinates\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_point_data\&.h>\fP
.PP
Inherits \fBQwtPointSeriesData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQwtCPointerValueData\fP (const T *y, size_t \fBsize\fP)"
.br
.ti -1c
.RI "virtual size_t \fBsize\fP () const override"
.br
.ti -1c
.RI "virtual QPointF \fBsample\fP (size_t index) const override"
.br
.ti -1c
.RI "const T * \fByData\fP () const"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.SS "template<typename T>
.br
class QwtCPointerValueData< T >"
Data class containing a pointer to memory of y coordinates\&. 

The memory contains the y coordinates, while the index is interpreted as x coordinate\&. 
.PP
Definition at line 89 of file qwt_point_data\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBQwtCPointerValueData\fP< T >::\fBQwtCPointerValueData\fP (const T * y, size_t size)"
Constructor
.PP
\fBParameters\fP
.RS 4
\fIy\fP Array of y values 
.br
\fIsize\fP Size of the x and y arrays
.RE
.PP
\fBWarning\fP
.RS 4
The programmer must assure that the memory blocks referenced by the pointers remain valid during the lifetime of the \fBQwtCPointerValueData\fP object\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBQwtPlotCurve::setData()\fP, \fBQwtPlotCurve::setRawSamples()\fP 
.RE
.PP

.PP
Definition at line 380 of file qwt_point_data\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > QPointF \fBQwtCPointerValueData\fP< T >::sample (size_t index) const\fC [override]\fP, \fC [virtual]\fP"
Return the sample at position i
.PP
\fBParameters\fP
.RS 4
\fIindex\fP Index 
.RE
.PP
\fBReturns\fP
.RS 4
Sample at position i 
.RE
.PP

.PP
Reimplemented from \fBQwtArraySeriesData< QPointF >\fP\&.
.PP
Definition at line 400 of file qwt_point_data\&.h\&.
.SS "template<typename T > size_t \fBQwtCPointerValueData\fP< T >::size\fC [override]\fP, \fC [virtual]\fP"

.PP
\fBReturns\fP
.RS 4
Size of the data set 
.RE
.PP

.PP
Reimplemented from \fBQwtArraySeriesData< QPointF >\fP\&.
.PP
Definition at line 388 of file qwt_point_data\&.h\&.
.SS "template<typename T > const T * \fBQwtCPointerValueData\fP< T >::yData"

.PP
\fBReturns\fP
.RS 4
Array of the y-values 
.RE
.PP

.PP
Definition at line 407 of file qwt_point_data\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
