.TH "QwtEventPattern::KeyPattern" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtEventPattern::KeyPattern \- A pattern for key events\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_event_pattern\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyPattern\fP (int keyCode=Qt::Key_unknown, Qt::KeyboardModifiers modifierCodes=Qt::NoModifier)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBkey\fP"
.br
.RI "Key code\&. "
.ti -1c
.RI "Qt::KeyboardModifiers \fBmodifiers\fP"
.br
.RI "Modifiers\&. "
.in -1c
.SH "Detailed Description"
.PP 
A pattern for key events\&. 
.PP
Definition at line 168 of file qwt_event_pattern\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
