.TH "QwtEventPattern::MousePattern" 3 "Sun Jul 18 2021" "Version 6.2.0" "Qwt User's Guide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtEventPattern::MousePattern \- A pattern for mouse events\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <qwt_event_pattern\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMousePattern\fP (Qt::MouseButton btn=Qt::NoButton, Qt::KeyboardModifiers modifierCodes=Qt::NoModifier)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Qt::MouseButton \fBbutton\fP"
.br
.RI "Button\&. "
.ti -1c
.RI "Qt::KeyboardModifiers \fBmodifiers\fP"
.br
.RI "Keyboard modifier\&. "
.in -1c
.SH "Detailed Description"
.PP 
A pattern for mouse events\&. 
.PP
Definition at line 149 of file qwt_event_pattern\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Qwt User's Guide from the source code\&.
