.TH "FloatArray" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FloatArray
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <processviewserver\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBf\fP [10]"
.br
.ti -1c
.RI "int \fBf0\fP"
.br
.ti -1c
.RI "int \fBf1\fP"
.br
.ti -1c
.RI "int \fBf2\fP"
.br
.ti -1c
.RI "int \fBf3\fP"
.br
.ti -1c
.RI "int \fBf4\fP"
.br
.ti -1c
.RI "int \fBf5\fP"
.br
.ti -1c
.RI "int \fBf6\fP"
.br
.ti -1c
.RI "int \fBf7\fP"
.br
.ti -1c
.RI "int \fBf8\fP"
.br
.ti -1c
.RI "int \fBf9\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "float FloatArray::f[10]"

.SS "int FloatArray::f0"

.SS "int FloatArray::f1"

.SS "int FloatArray::f2"

.SS "int FloatArray::f3"

.SS "int FloatArray::f4"

.SS "int FloatArray::f5"

.SS "int FloatArray::f6"

.SS "int FloatArray::f7"

.SS "int FloatArray::f8"

.SS "int FloatArray::f9"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
