.TH "glFont::Glyph" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glFont::Glyph
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBtex_x1\fP"
.br
.ti -1c
.RI "float \fBtex_y1\fP"
.br
.ti -1c
.RI "float \fBtex_x2\fP"
.br
.ti -1c
.RI "int \fBadvance\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int glFont::Glyph::advance"

.SS "float glFont::Glyph::tex_x1"

.SS "float glFont::Glyph::tex_x2"

.SS "float glFont::Glyph::tex_y1"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
