.TH "Hyperlink" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hyperlink
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpvHyperlink\fP (\fBPARAM\fP *p, const char *link)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These are the hyperlink routines 
.SH "Function Documentation"
.PP 
.SS "int pvHyperlink (\fBPARAM\fP * p, const char * link)"

.PP
.nf

Connect to a different server\&.
eg\&. link = 'pv://hostname:5050'
If you add '+' at the beginning of the URL a new pvbrowser will be started with that URL\&.
eg\&. link = '+pv://hostname:5050'
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
