.TH "PARSE_EVENT_STRUCT" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PARSE_EVENT_STRUCT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <processviewserver\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBevent\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "char \fBtext\fP [\fBMAX_EVENT_LENGTH\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int PARSE_EVENT_STRUCT::event"

.SS "int PARSE_EVENT_STRUCT::i"

.SS "char PARSE_EVENT_STRUCT::text[\fBMAX_EVENT_LENGTH\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
