.TH "pvAddressTable" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pvAddressTable
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <processviewserver\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBpvAddressTableItem\fP \fBadr\fP [\fBMAX_CLIENTS\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBpvAddressTableItem\fP pvAddressTable::adr[\fBMAX_CLIENTS\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
