.TH "pvAddressTableItem" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pvAddressTableItem
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <processviewserver\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBs\fP"
.br
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "unsigned char \fBadr\fP [16]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char pvAddressTableItem::adr[16]"

.SS "int pvAddressTableItem::s"

.SS "int pvAddressTableItem::version"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
