.TH "pvTime" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pvTime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <processviewserver\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBmillisecond\fP"
.br
.ti -1c
.RI "int \fBsecond\fP"
.br
.ti -1c
.RI "int \fBminute\fP"
.br
.ti -1c
.RI "int \fBhour\fP"
.br
.ti -1c
.RI "int \fBday\fP"
.br
.ti -1c
.RI "int \fBmonth\fP"
.br
.ti -1c
.RI "int \fByear\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int pvTime::day"

.SS "int pvTime::hour"

.SS "int pvTime::millisecond"

.SS "int pvTime::minute"

.SS "int pvTime::month"

.SS "int pvTime::second"

.SS "int pvTime::year"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
