.TH "QwtCounter" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtCounter
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtCounterSetStep\fP (\fBPARAM\fP *p, int id, float step)"
.br
.ti -1c
.RI "int \fBqwtCounterSetMinValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.ti -1c
.RI "int \fBqwtCounterSetMaxValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.ti -1c
.RI "int \fBqwtCounterSetStepButton1\fP (\fBPARAM\fP *p, int id, int n)"
.br
.ti -1c
.RI "int \fBqwtCounterSetStepButton2\fP (\fBPARAM\fP *p, int id, int n)"
.br
.ti -1c
.RI "int \fBqwtCounterSetStepButton3\fP (\fBPARAM\fP *p, int id, int n)"
.br
.ti -1c
.RI "int \fBqwtCounterSetNumButtons\fP (\fBPARAM\fP *p, int id, int n)"
.br
.ti -1c
.RI "int \fBqwtCounterSetIncSteps\fP (\fBPARAM\fP *p, int id, int button, int n)"
.br
.ti -1c
.RI "int \fBqwtCounterSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtCounter Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtCounterSetIncSteps (\fBPARAM\fP * p, int id, int button, int n)"

.PP
.nf

\fBCounterButton\fP\&.
.fi
.PP
 
.SS "int qwtCounterSetMaxValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetMinValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetNumButtons (\fBPARAM\fP * p, int id, int n)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetStep (\fBPARAM\fP * p, int id, float step)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetStepButton1 (\fBPARAM\fP * p, int id, int n)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetStepButton2 (\fBPARAM\fP * p, int id, int n)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetStepButton3 (\fBPARAM\fP * p, int id, int n)"

.PP
.nf

.fi
.PP
 
.SS "int qwtCounterSetValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
