.TH "QwtDial" 3 "Tue Nov 22 2016" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtDial \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtDialSetRange\fP (\fBPARAM\fP *p, int id, float vmin, float vmax, float step=0\&.0f)"
.br
.ti -1c
.RI "int \fBqwtDialSetMass\fP (\fBPARAM\fP *p, int id, float mass)"
.br
.ti -1c
.RI "int \fBqwtDialSetReadOnly\fP (\fBPARAM\fP *p, int id, int rdonly)"
.br
.ti -1c
.RI "int \fBqwtDialSetFrameShadow\fP (\fBPARAM\fP *p, int id, int shadow)"
.br
.ti -1c
.RI "int \fBqwtDialShowBackground\fP (\fBPARAM\fP *p, int id, int show)"
.br
.ti -1c
.RI "int \fBqwtDialSetLineWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtDialSetMode\fP (\fBPARAM\fP *p, int id, int mode)"
.br
.ti -1c
.RI "int \fBqwtDialSetWrapping\fP (\fBPARAM\fP *p, int id, int wrap)"
.br
.ti -1c
.RI "int \fBqwtDialSetScale\fP (\fBPARAM\fP *p, int id, int maxMajIntv, int maxMinIntv, float step)"
.br
.ti -1c
.RI "int \fBqwtDialSetScaleArc\fP (\fBPARAM\fP *p, int id, float min, float max)"
.br
.ti -1c
.RI "int \fBqwtDialSetOrigin\fP (\fBPARAM\fP *p, int id, float o)"
.br
.ti -1c
.RI "int \fBqwtDialSetNeedle\fP (\fBPARAM\fP *p, int id, int which, int r1=0, int g1=0, int b1=0, int r2=255, int g2=255, int b2=255, int r3=128, int g3=128, int b3=128)"
.br
.ti -1c
.RI "int \fBqwtDialSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtDial Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtDialSetFrameShadow (\fBPARAM\fP *p, intid, intshadow)"

.PP
.nf

\fBDialShadow\fP\&.
.fi
.PP
 
.SS "int qwtDialSetLineWidth (\fBPARAM\fP *p, intid, intwidth)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetMass (\fBPARAM\fP *p, intid, floatmass)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetMode (\fBPARAM\fP *p, intid, intmode)"

.PP
.nf

\fBDialMode\fP\&.
.fi
.PP
 
.SS "int qwtDialSetNeedle (\fBPARAM\fP *p, intid, intwhich, intr1 = \fC0\fP, intg1 = \fC0\fP, intb1 = \fC0\fP, intr2 = \fC255\fP, intg2 = \fC255\fP, intb2 = \fC255\fP, intr3 = \fC128\fP, intg3 = \fC128\fP, intb3 = \fC128\fP)"

.PP
.nf

which = \fBDialNeedle\fP\&.
.fi
.PP
 
.SS "int qwtDialSetOrigin (\fBPARAM\fP *p, intid, floato)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetRange (\fBPARAM\fP *p, intid, floatvmin, floatvmax, floatstep = \fC0\&.0f\fP)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetReadOnly (\fBPARAM\fP *p, intid, intrdonly)"

.PP
.nf

rdonly = 0 | 1
.fi
.PP
 
.SS "int qwtDialSetScale (\fBPARAM\fP *p, intid, intmaxMajIntv, intmaxMinIntv, floatstep)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetScaleArc (\fBPARAM\fP *p, intid, floatmin, floatmax)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetValue (\fBPARAM\fP *p, intid, floatvalue)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialSetWrapping (\fBPARAM\fP *p, intid, intwrap)"

.PP
.nf

.fi
.PP
 
.SS "int qwtDialShowBackground (\fBPARAM\fP *p, intid, intshow)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
