.TH "QwtKnob" 3 "Tue Nov 22 2016" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtKnob \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtKnobSetScale\fP (\fBPARAM\fP *p, int id, float min, float max, float step, int logarithmic)"
.br
.ti -1c
.RI "int \fBqwtKnobSetMass\fP (\fBPARAM\fP *p, int id, float mass)"
.br
.ti -1c
.RI "int \fBqwtKnobSetOrientation\fP (\fBPARAM\fP *p, int id, int orientation)"
.br
.ti -1c
.RI "int \fBqwtKnobSetReadOnly\fP (\fBPARAM\fP *p, int id, int rdonly)"
.br
.ti -1c
.RI "int \fBqwtKnobSetKnobWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtKnobSetTotalAngle\fP (\fBPARAM\fP *p, int id, float angle)"
.br
.ti -1c
.RI "int \fBqwtKnobSetBorderWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtKnobSetSymbol\fP (\fBPARAM\fP *p, int id, int symbol)"
.br
.ti -1c
.RI "int \fBqwtKnobSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtKnob Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtKnobSetBorderWidth (\fBPARAM\fP *p, intid, intwidth)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetKnobWidth (\fBPARAM\fP *p, intid, intwidth)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetMass (\fBPARAM\fP *p, intid, floatmass)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetOrientation (\fBPARAM\fP *p, intid, intorientation)"

.PP
.nf

orientation = HORIZONTAL|VERTICAL
.fi
.PP
 
.SS "int qwtKnobSetReadOnly (\fBPARAM\fP *p, intid, intrdonly)"

.PP
.nf

rdonly = 0 | 1
.fi
.PP
 
.SS "int qwtKnobSetScale (\fBPARAM\fP *p, intid, floatmin, floatmax, floatstep, intlogarithmic)"

.PP
.nf

logarithmic = 0 | 1
.fi
.PP
 
.SS "int qwtKnobSetSymbol (\fBPARAM\fP *p, intid, intsymbol)"

.PP
.nf

\fBKnobSymbol\fP\&.
.fi
.PP
 
.SS "int qwtKnobSetTotalAngle (\fBPARAM\fP *p, intid, floatangle)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetValue (\fBPARAM\fP *p, intid, floatvalue)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
