.TH "QwtKnob" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtKnob
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtKnobSetScale\fP (\fBPARAM\fP *p, int id, float min, float max, float step, int logarithmic)"
.br
.ti -1c
.RI "int \fBqwtKnobSetMass\fP (\fBPARAM\fP *p, int id, float mass)"
.br
.ti -1c
.RI "int \fBqwtKnobSetOrientation\fP (\fBPARAM\fP *p, int id, int orientation)"
.br
.ti -1c
.RI "int \fBqwtKnobSetReadOnly\fP (\fBPARAM\fP *p, int id, int rdonly)"
.br
.ti -1c
.RI "int \fBqwtKnobSetKnobWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtKnobSetTotalAngle\fP (\fBPARAM\fP *p, int id, float angle)"
.br
.ti -1c
.RI "int \fBqwtKnobSetBorderWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtKnobSetSymbol\fP (\fBPARAM\fP *p, int id, int symbol)"
.br
.ti -1c
.RI "int \fBqwtKnobSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtKnob Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtKnobSetBorderWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetKnobWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetMass (\fBPARAM\fP * p, int id, float mass)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetOrientation (\fBPARAM\fP * p, int id, int orientation)"

.PP
.nf

orientation = HORIZONTAL|VERTICAL
.fi
.PP
 
.SS "int qwtKnobSetReadOnly (\fBPARAM\fP * p, int id, int rdonly)"

.PP
.nf

rdonly = 0 | 1
.fi
.PP
 
.SS "int qwtKnobSetScale (\fBPARAM\fP * p, int id, float min, float max, float step, int logarithmic)"

.PP
.nf

logarithmic = 0 | 1
.fi
.PP
 
.SS "int qwtKnobSetSymbol (\fBPARAM\fP * p, int id, int symbol)"

.PP
.nf

\fBKnobSymbol\fP\&.
.fi
.PP
 
.SS "int qwtKnobSetTotalAngle (\fBPARAM\fP * p, int id, float angle)"

.PP
.nf

.fi
.PP
 
.SS "int qwtKnobSetValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
