.TH "QwtSlider" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtSlider
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtSliderSetScale\fP (\fBPARAM\fP *p, int id, float min, float max, float step, int logarithmic)"
.br
.ti -1c
.RI "int \fBqwtSliderSetMass\fP (\fBPARAM\fP *p, int id, float mass)"
.br
.ti -1c
.RI "int \fBqwtSliderSetOrientation\fP (\fBPARAM\fP *p, int id, int orientation)"
.br
.ti -1c
.RI "int \fBqwtSliderSetReadOnly\fP (\fBPARAM\fP *p, int id, int rdonly)"
.br
.ti -1c
.RI "int \fBqwtSliderSetBgStyle\fP (\fBPARAM\fP *p, int id, int style)"
.br
.ti -1c
.RI "int \fBqwtSliderSetScalePos\fP (\fBPARAM\fP *p, int id, int pos)"
.br
.ti -1c
.RI "int \fBqwtSliderSetThumbLength\fP (\fBPARAM\fP *p, int id, int length)"
.br
.ti -1c
.RI "int \fBqwtSliderSetThumbWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtSliderSetBorderWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtSliderSetMargins\fP (\fBPARAM\fP *p, int id, int x, int y)"
.br
.ti -1c
.RI "int \fBqwtSliderSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtSlider Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtSliderSetBgStyle (\fBPARAM\fP * p, int id, int style)"

.PP
.nf

\fBSliderBGSTYLE\fP\&.
.fi
.PP
 
.SS "int qwtSliderSetBorderWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtSliderSetMargins (\fBPARAM\fP * p, int id, int x, int y)"

.PP
.nf

.fi
.PP
 
.SS "int qwtSliderSetMass (\fBPARAM\fP * p, int id, float mass)"

.PP
.nf

.fi
.PP
 
.SS "int qwtSliderSetOrientation (\fBPARAM\fP * p, int id, int orientation)"

.PP
.nf

orientation = HORIZONTAL|VERTICAL
.fi
.PP
 
.SS "int qwtSliderSetReadOnly (\fBPARAM\fP * p, int id, int rdonly)"

.PP
.nf

rdonly = 0 | 1
.fi
.PP
 
.SS "int qwtSliderSetScale (\fBPARAM\fP * p, int id, float min, float max, float step, int logarithmic)"

.PP
.nf

logarithmic = 0 | 1
.fi
.PP
 
.SS "int qwtSliderSetScalePos (\fBPARAM\fP * p, int id, int pos)"

.PP
.nf

.fi
.PP
 
.SS "int qwtSliderSetThumbLength (\fBPARAM\fP * p, int id, int length)"

.PP
.nf

.fi
.PP
 
.SS "int qwtSliderSetThumbWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtSliderSetValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
