.TH "QwtScale" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtScale
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtScaleSetTitle\fP (\fBPARAM\fP *p, int id, const char *text)"
.br
.ti -1c
.RI "int \fBqwtScaleSetTitleColor\fP (\fBPARAM\fP *p, int id, int r, int g, int b)"
.br
.ti -1c
.RI "int \fBqwtScaleSetTitleFont\fP (\fBPARAM\fP *p, int id, const char *family, int pointsize, int bold, int italic, int underline, int strikeout)"
.br
.ti -1c
.RI "int \fBqwtScaleSetTitleAlignment\fP (\fBPARAM\fP *p, int id, int flags)"
.br
.ti -1c
.RI "int \fBqwtScaleSetBorderDist\fP (\fBPARAM\fP *p, int id, int start, int end)"
.br
.ti -1c
.RI "int \fBqwtScaleSetBaselineDist\fP (\fBPARAM\fP *p, int id, int bd)"
.br
.ti -1c
.RI "int \fBqwtScaleSetScaleDiv\fP (\fBPARAM\fP *p, int id, float lBound, float hBound, int maxMaj, int maxMin, int log, float step, int ascend)"
.br
.ti -1c
.RI "int \fBqwtScaleSetLabelFormat\fP (\fBPARAM\fP *p, int id, int f, int prec, int fieldWidth)"
.br
.ti -1c
.RI "int \fBqwtScaleSetLabelAlignment\fP (\fBPARAM\fP *p, int id, int align)"
.br
.ti -1c
.RI "int \fBqwtScaleSetLabelRotation\fP (\fBPARAM\fP *p, int id, float rotation)"
.br
.ti -1c
.RI "int \fBqwtScaleSetPosition\fP (\fBPARAM\fP *p, int id, int position)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtScale Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtScaleSetBaselineDist (\fBPARAM\fP * p, int id, int bd)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetBorderDist (\fBPARAM\fP * p, int id, int start, int end)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetLabelAlignment (\fBPARAM\fP * p, int id, int align)"

.PP
.nf

\fBScalePosition\fP\&.
.fi
.PP
 
.SS "int qwtScaleSetLabelFormat (\fBPARAM\fP * p, int id, int f, int prec, int fieldWidth)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetLabelRotation (\fBPARAM\fP * p, int id, float rotation)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetPosition (\fBPARAM\fP * p, int id, int position)"

.PP
.nf

\fBScalePosition\fP\&.
.fi
.PP
 
.SS "int qwtScaleSetScaleDiv (\fBPARAM\fP * p, int id, float lBound, float hBound, int maxMaj, int maxMin, int log, float step, int ascend)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetTitle (\fBPARAM\fP * p, int id, const char * text)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetTitleAlignment (\fBPARAM\fP * p, int id, int flags)"

.PP
.nf

\fBScalePosition\fP\&.
.fi
.PP
 
.SS "int qwtScaleSetTitleColor (\fBPARAM\fP * p, int id, int r, int g, int b)"

.PP
.nf

.fi
.PP
 
.SS "int qwtScaleSetTitleFont (\fBPARAM\fP * p, int id, const char * family, int pointsize, int bold, int italic, int underline, int strikeout)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
