.TH "QwtThermo" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtThermo
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtThermoSetScale\fP (\fBPARAM\fP *p, int id, float min, float max, float step, int logarithmic)"
.br
.ti -1c
.RI "int \fBqwtThermoSetOrientation\fP (\fBPARAM\fP *p, int id, int orientation, int position)"
.br
.ti -1c
.RI "int \fBqwtThermoSetBorderWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtThermoSetFillColor\fP (\fBPARAM\fP *p, int id, int r, int g, int b)"
.br
.ti -1c
.RI "int \fBqwtThermoSetAlarmColor\fP (\fBPARAM\fP *p, int id, int r, int g, int b)"
.br
.ti -1c
.RI "int \fBqwtThermoSetAlarmLevel\fP (\fBPARAM\fP *p, int id, float level)"
.br
.ti -1c
.RI "int \fBqwtThermoSetAlarmEnabled\fP (\fBPARAM\fP *p, int id, int tf)"
.br
.ti -1c
.RI "int \fBqwtThermoSetPipeWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtThermoSetRange\fP (\fBPARAM\fP *p, int id, float vmin, float vmax, float step=0\&.0f)"
.br
.ti -1c
.RI "int \fBqwtThermoSetMargin\fP (\fBPARAM\fP *p, int id, int margin)"
.br
.ti -1c
.RI "int \fBqwtThermoSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtThermo Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtThermoSetAlarmColor (\fBPARAM\fP * p, int id, int r, int g, int b)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetAlarmEnabled (\fBPARAM\fP * p, int id, int tf)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetAlarmLevel (\fBPARAM\fP * p, int id, float level)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetBorderWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetFillColor (\fBPARAM\fP * p, int id, int r, int g, int b)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetMargin (\fBPARAM\fP * p, int id, int margin)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetOrientation (\fBPARAM\fP * p, int id, int orientation, int position)"

.PP
.nf

orientation = HORIZONTAL|VERTICAL
\fBThermoPosition\fP\&.
.fi
.PP
 
.SS "int qwtThermoSetPipeWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetRange (\fBPARAM\fP * p, int id, float vmin, float vmax, float step = \fC0\&.0f\fP)"

.PP
.nf

.fi
.PP
 
.SS "int qwtThermoSetScale (\fBPARAM\fP * p, int id, float min, float max, float step, int logarithmic)"

.PP
.nf

logarithmic = 0 | 1
.fi
.PP
 
.SS "int qwtThermoSetValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
