.TH "QwtWheel" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QwtWheel
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBqwtWheelSetMass\fP (\fBPARAM\fP *p, int id, float mass)"
.br
.ti -1c
.RI "int \fBqwtWheelSetOrientation\fP (\fBPARAM\fP *p, int id, int orientation)"
.br
.ti -1c
.RI "int \fBqwtWheelSetReadOnly\fP (\fBPARAM\fP *p, int id, int rdonly)"
.br
.ti -1c
.RI "int \fBqwtWheelSetTotalAngle\fP (\fBPARAM\fP *p, int id, float angle)"
.br
.ti -1c
.RI "int \fBqwtWheelSetTickCnt\fP (\fBPARAM\fP *p, int id, int cnt)"
.br
.ti -1c
.RI "int \fBqwtWheelSetViewAngle\fP (\fBPARAM\fP *p, int id, float angle)"
.br
.ti -1c
.RI "int \fBqwtWheelSetInternalBorder\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtWheelSetWheelWidth\fP (\fBPARAM\fP *p, int id, int width)"
.br
.ti -1c
.RI "int \fBqwtWheelSetValue\fP (\fBPARAM\fP *p, int id, float value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
QwtWheel Widget 
.SH "Function Documentation"
.PP 
.SS "int qwtWheelSetInternalBorder (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SS "int qwtWheelSetMass (\fBPARAM\fP * p, int id, float mass)"

.PP
.nf

.fi
.PP
 
.SS "int qwtWheelSetOrientation (\fBPARAM\fP * p, int id, int orientation)"

.PP
.nf

orientation = HORIZONTAL|VERTICAL
.fi
.PP
 
.SS "int qwtWheelSetReadOnly (\fBPARAM\fP * p, int id, int rdonly)"

.PP
.nf

rdonly = 0 | 1
.fi
.PP
 
.SS "int qwtWheelSetTickCnt (\fBPARAM\fP * p, int id, int cnt)"

.PP
.nf

.fi
.PP
 
.SS "int qwtWheelSetTotalAngle (\fBPARAM\fP * p, int id, float angle)"

.PP
.nf

.fi
.PP
 
.SS "int qwtWheelSetValue (\fBPARAM\fP * p, int id, float value)"

.PP
.nf

.fi
.PP
 
.SS "int qwtWheelSetViewAngle (\fBPARAM\fP * p, int id, float angle)"

.PP
.nf

.fi
.PP
 
.SS "int qwtWheelSetWheelWidth (\fBPARAM\fP * p, int id, int width)"

.PP
.nf

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
