.TH "UnitConversion" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnitConversion
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBunit\fP (\fBPARAM\fP *p, float val, int conversion)"
.br
.in -1c
.SH "Detailed Description"
.PP 
unit 
.SH "Function Documentation"
.PP 
.SS "float unit (\fBPARAM\fP * p, float val, int conversion)"

.PP
.nf

\fBUNIT_CONVERSION\fP\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
