.TH "VTK" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VTK
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBpvVtkTcl\fP (\fBPARAM\fP *p, int id, const char *tcl_command)"
.br
.ti -1c
.RI "int \fBpvVtkTclPrintf\fP (\fBPARAM\fP *p, int id, const char *format,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBpvVtkTclScript\fP (\fBPARAM\fP *p, int id, const char *filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
These are the vtk output routines 
.SH "Function Documentation"
.PP 
.SS "int pvVtkTcl (\fBPARAM\fP * p, int id, const char * tcl_command)"

.PP
.nf

Send a single Tcl command to the widget
.fi
.PP
 
.SS "int pvVtkTclPrintf (\fBPARAM\fP * p, int id, const char * format,  \&.\&.\&.)"

.PP
.nf

Send a single Tcl command to the widget\&. Used like printf()
.fi
.PP
 
.SS "int pvVtkTclScript (\fBPARAM\fP * p, int id, const char * filename)"

.PP
.nf

Send a file with Tcl commands to the widget\&.
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
