.TH "WSEMAPHORE" 3 "Thu Sep 28 2023" "ProcessViewBrowser-ServerProgramming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WSEMAPHORE
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <wthread\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcmax\fP"
.br
.ti -1c
.RI "int \fBnready\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBmutex\fP"
.br
.ti -1c
.RI "pthread_cond_t \fBcond\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int WSEMAPHORE::cmax"

.SS "pthread_cond_t WSEMAPHORE::cond"

.SS "pthread_mutex_t WSEMAPHORE::mutex"

.SS "int WSEMAPHORE::nready"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProcessViewBrowser-ServerProgramming from the source code\&.
