######################################################################
# Automatically generated by qmake (1.07a) Sat Apr 8 14:34:18 2006
######################################################################

TEMPLATE = app
CONFIG  += warn_on release console 
CONFIG  -= qt
QMAKE_LFLAGS += -static-libgcc
INCLUDEPATH += .

# Input
# HEADERS += rlfind.h
SOURCES += rlfind.cpp
TARGET = rlfind
