cp ~/cc/priv/cvs/ProcessView/processview/processview/vtkQGLRenderWindow.h     .
cp ~/cc/priv/cvs/ProcessView/processview/processview/MyWidgets.h              .
cp ~/cc/priv/cvs/ProcessView/processview/processview/qwtplotwidget.h          .
cp ~/cc/priv/cvs/ProcessView/processview/processview/qimagewidget.h           .
cp ~/cc/priv/cvs/ProcessView/processview/processview/pvglwidget.h             .
cp ~/cc/priv/cvs/ProcessView/processview/processview/pvVtkTclWidget.h         .
cp ~/cc/priv/cvs/ProcessView/processview/processview/vtkQGLWidget.h           .
cp ~/cc/priv/cvs/ProcessView/processview/processview/qdrawwidget.h            .
cp ~/cc/priv/cvs/ProcessView/processview/processview/pvVtkTclWidget.cpp       .
cp ~/cc/priv/cvs/ProcessView/processview/processview/QDrawWidget.cpp          .
cp ~/cc/priv/cvs/ProcessView/processview/processview/MyWidgets.cpp            .
cp ~/cc/priv/cvs/ProcessView/processview/processview/tkAppInit.cpp            .
cp ~/cc/priv/cvs/ProcessView/processview/processview/pvglwidget.cpp           .
cp ~/cc/priv/cvs/ProcessView/processview/processview/vtkQGLWidget.cpp         .
cp ~/cc/priv/cvs/ProcessView/processview/processview/gldecode.cpp             .
cp ~/cc/priv/cvs/ProcessView/processview/processview/qwtplotwidget.cpp        .
cp ~/cc/priv/cvs/ProcessView/processview/processview/QImageWidget.cpp         .
cp ~/cc/priv/cvs/ProcessView/processview/processview/vtkQGLRenderWindow.cpp   .


qt3to4 -alwaysOverwrite vtkQGLRenderWindow.h
qt3to4 -alwaysOverwrite MyWidgets.h
qt3to4 -alwaysOverwrite qwtplotwidget.h
qt3to4 -alwaysOverwrite qimagewidget.h
qt3to4 -alwaysOverwrite pvglwidget.h
qt3to4 -alwaysOverwrite pvVtkTclWidget.h
qt3to4 -alwaysOverwrite vtkQGLWidget.h
qt3to4 -alwaysOverwrite qdrawwidget.h
qt3to4 -alwaysOverwrite pvVtkTclWidget.cpp
qt3to4 -alwaysOverwrite QDrawWidget.cpp
qt3to4 -alwaysOverwrite MyWidgets.cpp
qt3to4 -alwaysOverwrite tkAppInit.cpp
qt3to4 -alwaysOverwrite pvglwidget.cpp
qt3to4 -alwaysOverwrite vtkQGLWidget.cpp
qt3to4 -alwaysOverwrite gldecode.cpp
qt3to4 -alwaysOverwrite qwtplotwidget.cpp
qt3to4 -alwaysOverwrite QImageWidget.cpp
qt3to4 -alwaysOverwrite vtkQGLRenderWindow.cpp
