#! /bin/sh
# Copyright (c) 1995-2000 SuSE GmbH Nuernberg, Germany.
#
# Author: Kurt Garloff <feedback@suse.de>
#
# init.d/CIFdrv
#
#   and symbolic its link
#
# /sbin/rcCIFdrv
#
# System startup script for the CIF device driver
#
### BEGIN INIT INFO
# Provides: CIFdrv
# Required-Start: $local_fs
# Required-Stop:  
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Description:    Start CIF device Driver.
### END INIT INFO

# Source SuSE config
. /etc/rc.config

# Determine the base and follow a runlevel link name.
base=${0##*/}
link=${base#*[SK][0-9][0-9]}

# Force execution if not called by a runlevel directory.
test $link = $base && START_CIFDRV=yes
test "$START_CIFDRV" = yes || exit 0

CIFDRV_LOAD=/usr/sbin/CIFDRV_LOAD
CIFDRV_UNLOAD=/usr/sbin/CIFDRV_UNLOAD
test -x $CIFDRV_LOAD || exit 5
test -x $CIFDRV_UNLOAD || exit 5


# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status
. /etc/rc.status

# First reset status of this service
rc_reset

# Return values acc. to LSB for all commands but status:
# 0 - success
# 1 - misc error
# 2 - invalid or excess args
# 3 - unimplemented feature (e.g. reload)
# 4 - insufficient privilege
# 5 - program not installed
# 6 - program not configured
# 7 - program is not running
# 
# Note that starting an already running service, stopping
# or restarting a not-running service as well as the restart
# with force-reload (in case signalling is not supported) are
# considered a success.

case "$1" in
    start)
	echo -n "Starting CIF device driver "
	$CIFDRV_LOAD

	# Remember status and be verbose
	rc_status -v
	;;
    stop)
	echo -n "Shutting down CIF device driver "
	$CIFDRV_UNLOAD

	# Remember status and be verbose
	rc_status -v
	;;
    try-restart)
	## Stop the service and if this succeeds (i.e. the 
	## service was running before), start it again.
	$0 stop  &&  $0 start

	# Remember status and be quiet
	rc_status
	;;
    restart)
	## Stop the service and regardless of whether it was
	## running or not, start it again.
	$0 stop
	$0 start

	# Remember status and be quiet
	rc_status
	;;
    force-reload)
	#$0 stop  &&  $0 start
	#rc_status

	;;
    reload)
	#$0 stop  &&  $0 start
	#rc_status

	;;
    status)
	echo -n "Checking for CIF device driver: "
	#rc_status
	;;
    probe)
	## Optional: Probe for the necessity of a reload,
	## give out the argument which is required for a reload.

	##test ...
	;;
    *)
	echo "Usage: $0 {start|stop|status|try-restart|restart|force-reload|reload|probe}"
	exit 1
	;;
esac
rc_exit
